## Tensor Operations

In [6]:
import tensorflow as tf

# create tensors
tensor_a = tf.constant([[1, 2], [3, 4]])
tensor_b = tf.constant([[5, 6], [7, 8]])

# addition
result_add = tf.add(tensor_a, tensor_b)
print(result_add)

# subtraction
result_sub = tf.subtract(tensor_a, tensor_b)
print(result_sub)

# multiplication
result_mul = tf.multiply(tensor_a, tensor_b)
print(result_mul)

# division
result_div = tf.divide(tensor_a, tensor_b)
print(result_div)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[ 5 12]
 [21 32]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[0.2        0.33333333]
 [0.42857143 0.5       ]], shape=(2, 2), dtype=float64)


## Mathematical functions

In [11]:
# square
result_sqaure = tf.square(tensor_a)
print(result_sqaure)


tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


#### Reduction Operations

In [9]:
# sum along axis
result_sum = tf.reduce_sum(tensor_a, axis=1)
print(result_sum)

# mean along axis
result_mean = tf.reduce_mean(tensor_a)
print(result_mean)

# max along axis
result_max = tf.reduce_max(tensor_a)
print(result_max)

tf.Tensor([3 7], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


#### matrix operations

In [8]:
# Matrix Operations
result_matmul = tf.matmul(tensor_a, tensor_b)
print(result_matmul)

# Matrix transposition
result_transpose = tf.transpose(tensor_a)
print(result_transpose)



tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 3]
 [2 4]], shape=(2, 2), dtype=int32)


#### index and slicing/broadcasting

In [12]:
# accesing specfic element
element = tensor_a[0,0]

# slicing
slice_tensor = tensor_a[:,1]

# broadcasting
tensorc_c = tf.constant([1,2])
result_broadcast = tensor_a + tensorc_c
